version: '3'
volumes:
  db_data:
services:
  app:
    image: guoxiangke/nuxt-chat
    depends_on:
      - db
    build:
      context: .
      dockerfile: 'Dockerfile'
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./.env:/usr/src/app/.env
      # Uncomment 4 Dev
      # 把./bot排除在外，这样，每次修改代码，不用重复构建镜像，直接使用cache
      - ./1.memory-card.json:/usr/src/app/1.memory-card.json
      - ./server:/usr/src/app/server
      #   - ./server/database/db.sqlite:/usr/src/app/server/database/db.sqlite
      #   - ./server/models/imports:/usr/src/app/server/models/imports
      # - ./package.json:/usr/src/app/package.json
      # Uncomment on Local
      # - ../../../Downloads/Share/19_Psalm:/usr/src/app/files/19_Psalm # 4dev resources(mp3) for one cron task
  #MySQL Service
  db:
    image: mysql:latest
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
        '--default-authentication-plugin=mysql_native_password',
      ]
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: nuxtchat
      MYSQL_ROOT_PASSWORD: root
